from fpdf import FPDF

def generate_pdf(data, topic):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", 'B', 18)
    def ascii_safe(text):
        # Replace curly quotes and dashes with ASCII equivalents
        if not isinstance(text, str):
            return text
        return (
            text.replace('’', "'")
                .replace('‘', "'")
                .replace('“', '"')
                .replace('”', '"')
                .replace('–', '-')
                .replace('—', '-')
                .replace('…', '...')
        )

    pdf.cell(0, 12, ascii_safe(f"AI Knowledge Coach: {topic}"), ln=True, align='C')
    pdf.ln(8)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Structured Summary", ln=True)
    pdf.set_font("Arial", '', 12)
    pdf.multi_cell(0, 8, ascii_safe(data["summary"]))
    pdf.ln(4)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "5 Key Insights", ln=True)
    pdf.set_font("Arial", '', 12)
    for ins in data["insights"]:
        pdf.multi_cell(0, 8, ascii_safe(f"- {ins}"))
    pdf.ln(4)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "3 Interview Questions", ln=True)
    pdf.set_font("Arial", '', 12)
    for i, q in enumerate(data["interview_questions"], 1):
        pdf.multi_cell(0, 8, ascii_safe(f"{i}. {q}"))
    pdf.ln(4)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Knowledge Check Quiz (5 MCQs)", ln=True)
    pdf.set_font("Arial", '', 12)
    for i, q in enumerate(data["quiz"], 1):
        pdf.multi_cell(0, 8, ascii_safe(f"Q{i}. {q['question']}"))
        for opt in q['options']:
            pdf.multi_cell(0, 8, ascii_safe(f"   - {opt}"))
        pdf.multi_cell(0, 8, ascii_safe(f"Answer: {q['answer']}"))
        pdf.ln(2)
    pdf.ln(4)

    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 8, "Generated by AI Knowledge Coach", ln=True, align='R')

    # Return PDF as bytes for Streamlit download
    return pdf.output(dest='S').encode('latin-1')
